_target_: ripe.matcher.concurrent_matcher.ConcurrentMatcher
min_num_matches: 4
matcher:
  _target_: kornia.feature.DescriptorMatcher
  match_mode: "mnn"
  th: 0.7
robust_estimator:
  _target_: ripe.matcher.pose_estimator_poselib.PoseLibRelativePoseEstimator
